CREATE TABLE IF NOT EXISTS maintenance_tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticket_number VARCHAR(30) NOT NULL UNIQUE,
    customer_id INT DEFAULT NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_phone VARCHAR(30) NOT NULL,
    customer_email VARCHAR(150) DEFAULT NULL,
    device_brand VARCHAR(100) DEFAULT NULL,
    device_model VARCHAR(100) DEFAULT NULL,
    serial_number VARCHAR(100) DEFAULT NULL,
    issue_description TEXT NOT NULL,
    status ENUM('received', 'diagnosing', 'waiting_parts', 'in_repair', 'ready', 'delivered', 'cancelled') NOT NULL DEFAULT 'received',
    priority ENUM('normal', 'urgent') NOT NULL DEFAULT 'normal',
    estimated_cost DECIMAL(12,2) DEFAULT 0,
    repair_cost DECIMAL(12,2) DEFAULT 0,
    amount_paid DECIMAL(12,2) DEFAULT 0,
    payment_status ENUM('unpaid', 'partial', 'paid') NOT NULL DEFAULT 'unpaid',
    technician_notes TEXT,
    received_at DATE DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    delivered_at DATETIME DEFAULT NULL,
    source ENUM('shop', 'manual') NOT NULL DEFAULT 'manual',
    user_id INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_maintenance_status (status),
    INDEX idx_maintenance_created (created_at)
);
